### PR TITLE
Navigation Bar 

### LINKED ISSUE #12: Add Navigation Bar to the HomePage.dart
1. Adding navigation bar at the bottom.
2. It includes items such as Schedule, Medication, FloatingActionButton, Settings, and File Icon widgets.
3. Currently every Item will show some sort of message to the user on the homepage itself whenever the User taps on a particular one.
4. By tapping FloatingActionButton, It'll navigate to the PatientForm.dart as usual.

Screenshot_2021-05-16-00-30-33-35_79cd4e626f662bece259227a91b18e1b 1

### PR DESCRIPTION
**Pull request by shivlendra20**

### CODE REVIEW

**Comment by mohitsoni-dev** [comment]
@shivlendra20 good job. I want some changes here:
1. Move bottomTabNavigation to main.dart file.
2. On index 0 render HomePage from the main and for other indexes render a empty screen.
You can comment here and ask any query.

**Comment by shivlendra20** [comment]
> 
> 
> @shivlendra20 good job. I want some changes here:
> 
>     1. Move bottomTabNavigation to main.dart file.
> 
>     2. On index 0 render HomePage from the main and for other indexes render a empty screen.
>        You can comment here and ask any query.

@mohitsoni-dev What exactly I need to do with index 0 can u explain a little bit please

**Comment by mohitsoni-dev** [comment]
Right now you are just changing Text by clicking on bottom tabs.
```
body: Center(
        child: _widgetOptions.elementAt(_selectedIndex),
      ),
```
I want you to pass entire screen into body. Like this:
```
List<dynamic> screens = [Dashboard(), Settings(), Profile(),  ....etc];
```
```
body: screens[_selectedIndex];
```
Comment if still have doubts.

**Comment by mohitsoni-dev** [comment]
No need to shift BottomTabNavigator to main.dart I make above changes that I just wrote.

**Pull request merged**
